name: check
on:
  push:
    tags:
      - '*'
jobs:
  test:
    runs-on: ubuntu:latest
    steps:
      - name: Checkout
        run: actions/checkout@v3
      - name: Install deps
        run: go mod download
      - name: Test
        run: go test ./...

